
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import Yoda.*;

/**
 * Clase que implementa la interfaz de Yoda.
 *
 * @author Alberto Meana
 */
public class YodaPanel extends javax.swing.JFrame {

    private Yoda yoda;
    
    /**
     * Constructor por defecto de la interfaz de yoda.
     * 
     * 
     * @param yoda Instancia de Yoda.
     * @author Alberto Meana
     */
    public YodaPanel( Yoda yoda) {
        
        initComponents();
        
        this.yoda = yoda;
        this.yodaImg.setIcon( new ImageIcon( "assets/yoda.jpg" ) );
        this.getContentPane().setBackground( Color.BLACK );
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation( dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height/2 );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yodaImg = new javax.swing.JLabel();
        botonResucitar = new javax.swing.JButton();
        botonInforme = new javax.swing.JButton();
        infoText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(649, 700));

        yodaImg.setBackground(new java.awt.Color(0, 0, 0));
        yodaImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botonResucitar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        botonResucitar.setText("Resucitar, el server puedes intentar");
        botonResucitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResucitarActionPerformed(evt);
            }
        });

        botonInforme.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        botonInforme.setText("Informacion, pedir has de");
        botonInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInformeActionPerformed(evt);
            }
        });

        infoText.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        infoText.setForeground(new java.awt.Color(102, 255, 51));
        infoText.setText("¿Realizar que accion quieres, hmm?");
        infoText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        texto.setBackground(new java.awt.Color(0, 0, 0));
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        texto.setForeground(new java.awt.Color(51, 255, 51));
        texto.setRows(5);
        texto.setFocusable(false);
        jScrollPane1.setViewportView(texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonResucitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(yodaImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoText)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yodaImg, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonResucitar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonResucitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResucitarActionPerformed
        this.yoda.sendRequest();
        this.updateScreen();
    }//GEN-LAST:event_botonResucitarActionPerformed

    private void botonInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInformeActionPerformed
        this.yoda.sendQuery();
        this.updateScreen();
    }//GEN-LAST:event_botonInformeActionPerformed
    
    private void updateScreen(){
    
        String p = this.yoda.getResult();
        this.texto.setText( p );
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInforme;
    private javax.swing.JButton botonResucitar;
    private javax.swing.JLabel infoText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel yodaImg;
    // End of variables declaration//GEN-END:variables
}
